### ISSUE TITLE
Blocks turn invisible when used as part of a moving contraption from create mod (1.16.5)

### ISSUE THREAD

**Issue by dimasasus** [TheCBProject/CBMultipart#122]
All blocks added by the mod will turn invisible when part of a moving contraption from Create mod (v0.3.2). I get that it's a very niche interaction (and I'm not sure what exactly causes it), but it would be nice if it worked. Also it seems that before that interaction crashed the game (which it doesn't anymore).

**Comment by dimasasus** [comment]
upd.: upgraded CodeChikenLib to 4.0.5.438 and CBMultipart to 3.0.3.122, the issue is still there. Turning off optifine and other such measures didn't help. Logs don't show any errors related to CBM either.

**Comment by covers1624** [comment]
This is due to Create only attempting to get the block's BakedModel. Multiparts don't have Baked Models.

Compatibility for this is planned in the future.

**Comment by yokunjon** [comment]
> This is due to Create only attempting to get the block's BakedModel. Multiparts don't have Baked Models.
> 
> Compatibility for this is planned in the future.

Hey, what do you have in mind for the compatibility? If you can describe it, I'm happy to experiment with it and provide a PR.

**Comment by yokunjon** [comment]
@covers1624 Hey, sorry for the mention. I guess notifications don't work with closed issues, so thought of mentioning you. I investigated it and found out several issues with Create due to wrong collision calculation on their end, related to dynamic collisions. I'll create an issue, possibly a PR to solve it, soon. Only remaining issue is rendering at the moment. To my understanding, CCL uses its own rendering and Create using Flywheel conflicts with that. I have some experience with shaders and custom meshes, but I don't know much about Blaze3d or stuff. This is where I am at right now, still investigating it. I'd appreciate comment on this, thanks!

**Comment by covers1624** [comment]
The simplest solution to this issue is to have Create use the BlockRenderDispatcher and ask it to 'render' each block. Instead of trying to grab the BakedQuads for the block directly, as multiparts so not currently have BakedQuads. It is technecally possible to give them BakedQuads, however, this would be incredibly expensive.
