### ISSUE TITLE
Does not work with Java 8 or Java 16+

### ISSUE THREAD

**Issue by Jkosio23** [TheCBProject/CBMultipart#129]
https://paste.ee/p/perIX crashlog using jre 1.8.0_321
You've said java 16+ isn't supported but there's no way to download versions between 8 and 17 without an oracle.com account. unless you'd provide links to download the working versions of java, you shouldn't close this issue until support is added.

Edit: apparently the crashlog for the latest crashes just weren't being generated so that link is wrong, here's the log for trying to run it on java 8, i'm trying to run create above and beyond https://paste.ee/p/gv1Vt

**Comment by Jkosio23** [comment]
Realized the java 8 issue is something else, not CB Multipart, but the java 16+ support is still something that'll be needed in the future

**Comment by covers1624** [comment]
Your first crash report Is not running with Hava 8, it is using Java 17 as per this line `Java Version: 17.0.1, Oracle Corporation`. This is not supported on 1.16, You will need to use Java 8-15.

Your second crash report is due to a Forge bug with Java8 U32X.

You should be grabbing Java from [Adoptium](https://adoptium.net/).
