### ISSUE TITLE
[Forge 1.20.1] Exception from CB Multipart during game load

### ISSUE THREAD

**Issue by vizthex123** [TheCBProject/CBMultipart#161]
Excited to use these mods on 1.20, but alas it isn't working for me :'c

Log:
[latest.log](https://github.com/TheCBProject/CBMultipart/files/15181259/latest.log)

Downgrading to v3.3.0.143 fixes it and allows the game to load.

**Comment by covers1624** [comment]
Does this issue occur with just CCL and CBMultipart?

**Comment by HypeStarF** [comment]
It does indeed crash with the only mods being CCL and CBMultipart. Although i play on 1.20.1 the error is the same:

Caught exception during event FMLLoadCompleteEvent dispatch for modid cb_multipart

net.minecraftforge.fml.ModLoadingException: CBMultipart (cb_multipart) encountered an error during the complete event phase
7java.lang.NullPointerException: 

Cannot invoke "String.hashCode()" because "value2" is null

**Comment by covers1624** [comment]
This should be resolved in build 145.
